import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../../api/client';
import { Certificate } from '../../types';
import { StatusBadge } from '../../components/StatusBadge';
import {
  ShieldCheck,
  Download,
  QrCode,
  RefreshCw,
  Printer,
  FileText,
  Calendar,
  UserCheck,
  Scale,
  ExternalLink,
  Eye,
  CheckCircle2
} from 'lucide-react';

export const CertificatesList: React.FC = () => {
  const [certificates, setCertificates] = useState<Certificate[]>([]);
  const [selectedCert, setSelectedCert] = useState<Certificate | null>(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    api.certificates.list()
      .then(certs => {
        setCertificates(certs);
        if (certs.length > 0) {
          setSelectedCert(certs[0]);
        }
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const totalCerts = certificates.length;
  const validCerts = certificates.filter(c => c.status === 'VALID').length;
  const expiredCerts = certificates.filter(c => c.status === 'EXPIRED').length;

  return (
    <div className="space-y-4 text-slate-800">
      
      {/* Header */}
      <div className="bg-white p-5 rounded-md border border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-2xs">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-slate-900 tracking-tight">Digital Certificates</h1>
            <span className="text-[11px] font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded border border-slate-200">
              {totalCerts} Total
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Digital verification certificates and authenticity tokens generated by METRION.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Link
            to="/verify/demo"
            className="px-3 py-1.5 bg-white hover:bg-slate-50 text-slate-700 border border-slate-300 rounded text-xs font-semibold flex items-center gap-1.5 transition-colors"
          >
            <QrCode className="w-3.5 h-3.5 text-blue-600" /> Verify Certificate
          </Link>
        </div>
      </div>

      {loading ? (
        <div className="p-8 text-center text-xs text-slate-500 bg-white rounded-md border border-slate-200">
          Loading certificates...
        </div>
      ) : certificates.length === 0 ? (
        <div className="p-8 text-center bg-white rounded-md border border-slate-200 space-y-2">
          <ShieldCheck className="w-8 h-8 text-slate-300 mx-auto" />
          <p className="text-xs font-semibold text-slate-700">No certificates on record</p>
          <p className="text-[11px] text-slate-400">
            Certificates appear here once field verification is completed by an authorized officer.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
          
          {/* LEFT: Certificates Table / List (lg:col-span-7) */}
          <div className="lg:col-span-7 space-y-3">
            <div className="bg-white rounded-md border border-slate-200 shadow-2xs overflow-hidden">
              <div className="p-3 border-b border-slate-200 bg-slate-50 flex items-center justify-between">
                <span className="text-xs font-bold uppercase tracking-wider text-slate-700">
                  Issued Certificates
                </span>
                <span className="text-[11px] text-slate-500">
                  Select a certificate to inspect details
                </span>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs border-collapse">
                  <thead className="bg-slate-50 border-b border-slate-200 text-slate-600 uppercase tracking-wider font-semibold text-[11px]">
                    <tr>
                      <th className="px-3 py-2.5">Certificate ID</th>
                      <th className="px-3 py-2.5">Instrument ID</th>
                      <th className="px-3 py-2.5">Status</th>
                      <th className="px-3 py-2.5">Valid Until</th>
                      <th className="px-3 py-2.5 text-right">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {certificates.map(cert => {
                      const isSelected = selectedCert?.id === cert.id;
                      return (
                        <tr
                          key={cert.id}
                          onClick={() => setSelectedCert(cert)}
                          className={`cursor-pointer transition-colors ${
                            isSelected ? 'bg-blue-50/60 font-medium' : 'hover:bg-slate-50'
                          }`}
                        >
                          <td className="px-3 py-3">
                            <span className="font-mono font-bold text-slate-900 block">
                              {cert.certificate_number}
                            </span>
                            <span className="text-[11px] text-slate-500 font-sans">
                              {cert.manufacturer} {cert.model}
                            </span>
                          </td>
                          <td className="px-3 py-3 font-mono font-semibold text-[#0B2545]">
                            {cert.instrument_permanent_id}
                          </td>
                          <td className="px-3 py-3">
                            <StatusBadge status={cert.status} size="sm" />
                          </td>
                          <td className="px-3 py-3 font-mono text-slate-600">
                            {new Date(cert.valid_until_date).toLocaleDateString('en-IN')}
                          </td>
                          <td className="px-3 py-3 text-right">
                            <button
                              onClick={e => {
                                e.stopPropagation();
                                setSelectedCert(cert);
                              }}
                              className={`px-2 py-1 text-xs rounded font-semibold inline-flex items-center gap-1 ${
                                isSelected
                                  ? 'bg-[#0B2545] text-white'
                                  : 'bg-slate-100 hover:bg-slate-200 text-slate-700'
                              }`}
                            >
                              <Eye className="w-3 h-3" /> Details
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* RIGHT: Detailed Certificate View & Preview (lg:col-span-5) */}
          {selectedCert && (
            <div className="lg:col-span-5 space-y-3">
              <div className="bg-white rounded-md border border-slate-200 p-5 shadow-2xs space-y-4">
                
                {/* Header Strip */}
                <div className="flex items-start justify-between border-b border-slate-200 pb-3">
                  <div>
                    <span className="text-[10px] font-mono uppercase tracking-wider text-slate-400 font-semibold block">
                      Digital Certificate
                    </span>
                    <h2 className="text-base font-mono font-bold text-[#0B2545]">
                      {selectedCert.certificate_number}
                    </h2>
                  </div>
                  <StatusBadge status={selectedCert.status} />
                </div>

                {/* Left/Right Certificate Content Spec */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                  <div className="space-y-2">
                    <div>
                      <span className="text-[10px] text-slate-400 uppercase font-semibold block">Certificate ID</span>
                      <span className="font-mono font-bold text-slate-900">{selectedCert.certificate_number}</span>
                    </div>

                    <div>
                      <span className="text-[10px] text-slate-400 uppercase font-semibold block">Instrument ID</span>
                      <Link
                        to={`/owner/instruments/${selectedCert.instrument_id}`}
                        className="font-mono font-bold text-blue-700 hover:underline"
                      >
                        {selectedCert.instrument_permanent_id}
                      </Link>
                    </div>

                    <div>
                      <span className="text-[10px] text-slate-400 uppercase font-semibold block">Verification Type</span>
                      <span className="font-medium text-slate-800">Periodic Verification</span>
                    </div>

                    <div>
                      <span className="text-[10px] text-slate-400 uppercase font-semibold block">Issued Date</span>
                      <span className="font-mono text-slate-700">
                        {new Date(selectedCert.issue_date).toLocaleDateString('en-IN')}
                      </span>
                    </div>

                    <div>
                      <span className="text-[10px] text-slate-400 uppercase font-semibold block">Valid Until</span>
                      <span className="font-mono font-bold text-slate-900">
                        {new Date(selectedCert.valid_until_date).toLocaleDateString('en-IN')}
                      </span>
                    </div>

                    <div>
                      <span className="text-[10px] text-slate-400 uppercase font-semibold block">Officer</span>
                      <span className="font-medium text-slate-800">
                        {selectedCert.issuing_authority_name || 'METRION Verification Officer'}
                      </span>
                    </div>
                  </div>

                  {/* QR Code & Preview Box */}
                  <div className="bg-slate-50 rounded border border-slate-200 p-3.5 flex flex-col items-center justify-center text-center space-y-2">
                    <div className="bg-white p-2.5 rounded border border-slate-300 shadow-2xs inline-block">
                      <img
                        src={`https://api.qrserver.com/v1/create-qr-code/?size=110x110&data=${encodeURIComponent(
                          window.location.origin + '/verify/' + selectedCert.qr_token
                        )}`}
                        alt="Certificate QR Token"
                        className="w-24 h-24"
                        loading="lazy"
                      />
                    </div>
                    <span className="text-[11px] font-mono font-bold text-slate-700">
                      {selectedCert.qr_token.slice(0, 16)}...
                    </span>
                    <p className="text-[10px] text-slate-500 leading-tight">
                      Scan to authenticate certificate
                    </p>
                  </div>
                </div>

                {/* Actions */}
                <div className="pt-3 border-t border-slate-200 flex flex-wrap items-center gap-2">
                  <Link
                    to={`/verify/${selectedCert.qr_token}`}
                    className="flex-1 py-1.5 px-3 bg-white hover:bg-slate-50 text-slate-800 border border-slate-300 rounded text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors"
                  >
                    <Eye className="w-3.5 h-3.5 text-blue-600" /> View Certificate
                  </Link>

                  <a
                    href={`/uploads/cert_${selectedCert.certificate_number}.pdf`}
                    target="_blank"
                    rel="noreferrer"
                    className="flex-1 py-1.5 px-3 bg-[#0B2545] hover:bg-slate-800 text-white rounded text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors shadow-2xs"
                  >
                    <Download className="w-3.5 h-3.5" /> Download PDF
                  </a>

                  <button
                    onClick={() => window.print()}
                    className="py-1.5 px-3 bg-white hover:bg-slate-50 text-slate-700 border border-slate-300 rounded text-xs font-medium flex items-center justify-center gap-1 transition-colors cursor-pointer"
                  >
                    <Printer className="w-3.5 h-3.5" /> Print
                  </button>

                  {(selectedCert.status === 'EXPIRED') && (
                    <button
                      onClick={() => navigate(`/owner/applications/new?instrument_id=${selectedCert.instrument_id}&type=RE_VERIFICATION`)}
                      className="w-full py-1.5 px-3 bg-amber-600 hover:bg-amber-700 text-white rounded text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors cursor-pointer"
                    >
                      <RefreshCw className="w-3.5 h-3.5" /> Re-verify Instrument
                    </button>
                  )}
                </div>

                <div className="p-2.5 bg-slate-50 rounded border border-slate-200 text-[10px] text-slate-500">
                  Verified against METRION certificate records. Tamper-evident cryptographic signature attached.
                </div>

              </div>
            </div>
          )}

        </div>
      )}

    </div>
  );
};
